name: 'Certification Table Action Readme'
description: 'Update automatically README with Certifications from Back4App'
inputs:
  token:
    description: 'GITHUB_TOKEN'
    required: true
outputs:
  total:
    description: 'total certifications added'
runs:
  using: 'node20'
  main: 'dist/index.js'
